// Mock data for the Feira marketplace.
// Phone numbers are fake placeholders used to build wa.me links in the demo.

export const producers = [
  {
    id: 'p1',
    name: 'Sítio Boa Terra',
    farmer: 'João Mendes',
    location: 'Vale do Ribeira, São Paulo',
    avatar: '👨🏽‍🌾',
    whatsapp: '5511999990001',
    bio: 'Family farm growing root vegetables for three generations. We harvest by hand the same morning you order, no cold storage, no middlemen.',
    since: 2014,
  },
  {
    id: 'p2',
    name: 'Chácara Verde Vale',
    farmer: 'Maria Oliveira',
    location: 'Serra da Mantiqueira, Minas Gerais',
    avatar: '👩🏼‍🌾',
    whatsapp: '5511999990002',
    bio: 'Small orchard up in the hills. I grow avocados and citrus with no chemical pesticides — just good soil, sun and a lot of patience.',
    since: 2018,
  },
  {
    id: 'p3',
    name: 'Horta do Sol',
    farmer: 'Pedro Castro',
    location: 'Holambra, São Paulo',
    avatar: '🧑🏻‍🌾',
    whatsapp: '5511999990003',
    bio: 'Sun-grown greens and tomatoes picked fresh every dawn. Proud to feed my neighbours straight from the field.',
    since: 2020,
  },
]

export const products = [
  {
    id: 'prod1',
    producerId: 'p1',
    name: 'Sweet Potato',
    emoji: '🍠',
    color: '#e8590c',
    category: 'Roots',
    pricePerKg: 4.5,
    available: 120,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Orange-fleshed batata-doce, sweet and creamy. Pulled from the ground yesterday morning.',
  },
  {
    id: 'prod2',
    producerId: 'p1',
    name: 'Cassava',
    emoji: '🥔',
    color: '#a9844f',
    category: 'Roots',
    pricePerKg: 3.8,
    available: 80,
    unit: 'kg',
    harvestedDaysAgo: 2,
    description: 'Fresh mandioca, peels easily and cooks soft. Great for boiling or frying.',
  },
  {
    id: 'prod3',
    producerId: 'p2',
    name: 'Hass Avocado',
    emoji: '🥑',
    color: '#2f9e44',
    category: 'Fruit',
    pricePerKg: 9.0,
    available: 45,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Buttery hass avocados, picked firm so they ripen perfectly at your home in a few days.',
  },
  {
    id: 'prod4',
    producerId: 'p2',
    name: 'Pera Oranges',
    emoji: '🍊',
    color: '#f08c00',
    category: 'Fruit',
    pricePerKg: 5.2,
    available: 200,
    unit: 'kg',
    harvestedDaysAgo: 3,
    description: 'Juicy laranja pera, low acidity and very sweet. Perfect for fresh juice.',
  },
  {
    id: 'prod5',
    producerId: 'p2',
    name: 'Sicilian Lemons',
    emoji: '🍋',
    color: '#f5d000',
    category: 'Fruit',
    pricePerKg: 6.0,
    available: 60,
    unit: 'kg',
    harvestedDaysAgo: 2,
    description: 'Fragrant, thick-skinned lemons full of zest. Grown on the cooler side of the hill.',
  },
  {
    id: 'prod6',
    producerId: 'p3',
    name: 'Heirloom Tomatoes',
    emoji: '🍅',
    color: '#e03131',
    category: 'Vegetables',
    pricePerKg: 7.5,
    available: 35,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Vine-ripened heirloom tomatoes in mixed colours. Sweet, meaty and full of flavour.',
  },
  {
    id: 'prod7',
    producerId: 'p3',
    name: 'Curly Kale',
    emoji: '🥬',
    color: '#37b24d',
    category: 'Vegetables',
    pricePerKg: 8.0,
    available: 25,
    unit: 'kg',
    harvestedDaysAgo: 0,
    description: 'Crisp couve picked this dawn. Tender leaves, no bitterness.',
  },
  {
    id: 'prod8',
    producerId: 'p3',
    name: 'Sweet Corn',
    emoji: '🌽',
    color: '#f0a000',
    category: 'Vegetables',
    pricePerKg: 4.0,
    available: 90,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Tender milho verde, sweet kernels straight off the stalk.',
  },
]

export const categories = ['All', 'Fruit', 'Vegetables', 'Roots']
