// Dados de exemplo da feira Feira.
// Os números de WhatsApp são fictícios, usados só para montar os links wa.me na demonstração.

export const producers = [
  {
    id: 'p1',
    name: 'Sítio Boa Terra',
    farmer: 'João Mendes',
    location: 'Vale do Ribeira, São Paulo',
    photo: '/img/farmers/joao.jpg',
    whatsapp: '5511999990001',
    bio: 'Sítio de família que planta raízes há três gerações. A gente colhe na mão na mesma manhã do seu pedido — sem câmara fria e sem atravessador.',
    since: 2014,
  },
  {
    id: 'p2',
    name: 'Chácara Verde Vale',
    farmer: 'Maria Oliveira',
    location: 'Serra da Mantiqueira, Minas Gerais',
    photo: '/img/farmers/maria.jpg',
    whatsapp: '5511999990002',
    bio: 'Um pomar pequeno lá no alto da serra. Planto abacate e frutas cítricas sem veneno nenhum — só terra boa, sol e muita paciência.',
    since: 2018,
  },
  {
    id: 'p3',
    name: 'Horta do Sol',
    farmer: 'Pedro Castro',
    location: 'Holambra, São Paulo',
    photo: '/img/farmers/pedro.jpg',
    whatsapp: '5511999990003',
    bio: 'Verduras e tomates criados no sol, colhidos fresquinhos todo amanhecer. Tenho orgulho de alimentar a vizinhança direto da roça.',
    since: 2020,
  },
]

export const products = [
  {
    id: 'prod1',
    producerId: 'p1',
    name: 'Batata-doce',
    photo: '/img/produce/batata-doce.jpg',
    color: '#e8590c',
    category: 'Raízes',
    pricePerKg: 4.5,
    available: 120,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Batata-doce de polpa alaranjada, docinha e cremosa. Foi arrancada da terra ontem de manhã.',
  },
  {
    id: 'prod2',
    producerId: 'p1',
    name: 'Mandioca',
    photo: '/img/produce/mandioca.jpg',
    color: '#a9844f',
    category: 'Raízes',
    pricePerKg: 3.8,
    available: 80,
    unit: 'kg',
    harvestedDaysAgo: 2,
    description: 'Mandioca fresquinha, descasca fácil e cozinha bem molinha. Ótima pra cozinhar ou pra fritar.',
  },
  {
    id: 'prod3',
    producerId: 'p2',
    name: 'Abacate Hass',
    photo: '/img/produce/abacate.jpg',
    color: '#2f9e44',
    category: 'Frutas',
    pricePerKg: 9.0,
    available: 45,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Abacate Hass cremoso, colhido ainda firme pra amadurecer certinho na sua casa em poucos dias.',
  },
  {
    id: 'prod4',
    producerId: 'p2',
    name: 'Laranja-pera',
    photo: '/img/produce/laranja.jpg',
    color: '#f08c00',
    category: 'Frutas',
    pricePerKg: 5.2,
    available: 200,
    unit: 'kg',
    harvestedDaysAgo: 3,
    description: 'Laranja-pera bem suculenta, pouco ácida e bem doce. Perfeita pra fazer suco.',
  },
  {
    id: 'prod5',
    producerId: 'p2',
    name: 'Limão-siciliano',
    photo: '/img/produce/limao.jpg',
    color: '#f5d000',
    category: 'Frutas',
    pricePerKg: 6.0,
    available: 60,
    unit: 'kg',
    harvestedDaysAgo: 2,
    description: 'Limão-siciliano cheiroso, de casca grossa e bem perfumado. Plantado no lado mais fresco da serra.',
  },
  {
    id: 'prod6',
    producerId: 'p3',
    name: 'Tomate caipira',
    photo: '/img/produce/tomate.jpg',
    color: '#e03131',
    category: 'Verduras',
    pricePerKg: 7.5,
    available: 35,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Tomate caipira maduro no pé, em cores variadas. Docinho, carnudo e cheio de sabor.',
  },
  {
    id: 'prod7',
    producerId: 'p3',
    name: 'Couve-manteiga',
    photo: '/img/produce/couve.jpg',
    color: '#37b24d',
    category: 'Verduras',
    pricePerKg: 8.0,
    available: 25,
    unit: 'kg',
    harvestedDaysAgo: 0,
    description: 'Couve-manteiga colhida hoje de madrugada. Folhas macias e sem amargor.',
  },
  {
    id: 'prod8',
    producerId: 'p3',
    name: 'Milho verde',
    photo: '/img/produce/milho.jpg',
    color: '#f0a000',
    category: 'Verduras',
    pricePerKg: 4.0,
    available: 90,
    unit: 'kg',
    harvestedDaysAgo: 1,
    description: 'Milho verde bem tenrinho, com grãos doces direto da espiga.',
  },
]

export const categories = ['Tudo', 'Frutas', 'Verduras', 'Raízes']

// Imagens prontas para quem for cadastrar um produto sem ter foto própria.
export const produceLibrary = [
  { id: 'abacate', name: 'Abacate', image: '/img/produce/abacate.jpg', color: '#2f9e44', category: 'Frutas' },
  { id: 'laranja', name: 'Laranja', image: '/img/produce/laranja.jpg', color: '#f08c00', category: 'Frutas' },
  { id: 'limao', name: 'Limão', image: '/img/produce/limao.jpg', color: '#f5d000', category: 'Frutas' },
  { id: 'morango', name: 'Morango', image: '/img/produce/morango.jpg', color: '#e64980', category: 'Frutas' },
  { id: 'uva', name: 'Uva', image: '/img/produce/uva.jpg', color: '#9c36b5', category: 'Frutas' },
  { id: 'tomate', name: 'Tomate', image: '/img/produce/tomate.jpg', color: '#e03131', category: 'Verduras' },
  { id: 'couve', name: 'Couve', image: '/img/produce/couve.jpg', color: '#37b24d', category: 'Verduras' },
  { id: 'milho', name: 'Milho', image: '/img/produce/milho.jpg', color: '#f0a000', category: 'Verduras' },
  { id: 'pimentao', name: 'Pimentão', image: '/img/produce/pimentao.jpg', color: '#2b8a3e', category: 'Verduras' },
  { id: 'cenoura', name: 'Cenoura', image: '/img/produce/cenoura.jpg', color: '#e8590c', category: 'Verduras' },
  { id: 'berinjela', name: 'Berinjela', image: '/img/produce/berinjela.jpg', color: '#7048e8', category: 'Verduras' },
  { id: 'cebola', name: 'Cebola', image: '/img/produce/cebola.jpg', color: '#d9a066', category: 'Verduras' },
  { id: 'batata-doce', name: 'Batata-doce', image: '/img/produce/batata-doce.jpg', color: '#e8590c', category: 'Raízes' },
  { id: 'mandioca', name: 'Mandioca', image: '/img/produce/mandioca.jpg', color: '#a9844f', category: 'Raízes' },
]

// Fotos de perfil prontas para quem não quiser enviar a própria.
export const avatarLibrary = [
  '/img/farmers/a1.jpg',
  '/img/farmers/a2.jpg',
  '/img/farmers/a3.jpg',
  '/img/farmers/a4.jpg',
  '/img/farmers/joao.jpg',
  '/img/farmers/maria.jpg',
]
